### ISSUE TITLE
Spamming resurrection macro

### ISSUE THREAD

**Issue by TheCruxDev** [OreaDev/libBetterBot#62]
The bot spams the resurrection macro even when it has to wait a certain time before it can actually get back to life. This is not causing any issues but is just for the beauty.

**Comment by DominicEliot** [comment]
It does cause issues. When running in RDP the input can lag causing the bot to miss the "/" and say something in chat. Also it makes it really hard to do other things with the bot while it's waiting (like chat or move to a better spot). 

However I think this issue is a small part of a bigger issue: The bot relies on chat commands to do a lot of things that should be done via game addons. Examples I can think of: Release, Repop, starting quest script, resetting the view.

It would be ideal if there was a API call that you could pass any "/" command to and it  would run it without using chat commands. I'm not sure if that is possible within the limitations of only using read memory processes. An alternative would be to make an addon with special hotkeys that performs the most common commands using non-character keybinds. The addon LazyPig can already a lot of these things (pressing ctrl+alt will release a corpse, and then pressing it again will repop).

**Comment by OreaDev** [comment]
This is fixed in the latest build

**Comment by OreaDev** [comment]
but feel free to comment back here if there are still issues and I can re-open this
